let fruits=['apple','banana','orange']
console.log(fruits[0])
fruits.push("mango")
console.log(fruits)
fruits.pop()
console.log(fruits)
fruits.unshift('grape')
console.log(fruits)
fruits.shift()
console.log(fruits)
